{% set name = "yatiml" %}
{% set version = "0.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}
source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 30eb62a51b9f60df095ff709a881c576b0c720b6dcd10994dde73872c4a1e1f4

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - python >=3.8
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - pyyaml >=5.1,!=5.4.1
    - typing_extensions

test:
  imports:
    - {{ name }}
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/yatiml/yatiml
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: "Reading, checking and writing YAML from Python"

extra:
  recipe-maintainers:
    - LourensVeen
